config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#splash_page', as: :spash_page
  get 'home' => 'static_pages#home', as: :home
  get 'static_pages/todolist' => 'static_pages#todolist', as: :todolist
  get 'static_pages/all_inventory_offered' => 'static_pages#all_inventory_offered', as: :all_inventory_offered

  resources :inventory_categories do
    resources :inventories
  end

  resources :accessory_categories do
    resources :accessories
  end

  get 'contact' => 'static_pages#contact', as: :contact

end

app/models/accessory.rb
class Accessory < ActiveRecord::Base
	has_attached_file :image, styles: { small: "100x100", med: "500x500", large: "1000x1000" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
	belongs_to :accessory_category
end

app/models/accessory_category.rb
class AccessoryCategory < ActiveRecord::Base
	has_many :accessories
end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
	has_attached_file :image, styles: { small: "100x100", med: "500x500", large: "1000x1000" }
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
	belongs_to :inventory_category
end

app/models/inventory_category.rb
class InventoryCategory < ActiveRecord::Base
	has_many :inventories
end

app/controllers/accessories_controller.rb
class AccessoriesController < ApplicationController
	def index
    @accessory_category = AccessoryCategory.find(params[:accessory_category_id])
		@accessories = @accessory_category.accessories
	end

	def show
		@accessory_category = AccessoryCategory.find(params[:accessory_category_id])
    @accessory = @accessory_category.accessories.find(params[:id])
	end

	def new
		@accessory_category = AccessoryCategory.find(params[:accessory_category_id])
    @accessory = @accessory_category.accessories.build
	end

	def edit
    @accessory_category = AccessoryCategory.find(params[:accessory_category_id])
    @accessory = @accessory_category.accessories.find(params[:id])
	end

	def create
		@accessory_category = AccessoryCategory.find(params[:accessory_category_id])
    @accessory = @accessory_category.accessories.build(accessory_params)

    if @accessory.save
      redirect_to accessory_categories_path, notice: 'Accessory was successfully created.'
    else
      render :new
    end
	end

	def update
    @accessory_category = AccessoryCategory.find(params[:accessory_category_id])
    @accessory = @accessory_category.accessories.find(params[:id])

    if @accessory.update(accessory_params)
      redirect_to accessory_categories_path, notice: 'Accessory was successfully created.'
    else
      render :edit
    end
  end

  def destroy
  	@accessory_category = AccessoryCategory.find(params[:accessory_category_id])
    @accessory = Accessory.find(params[:id])
    @accessory.destroy

    redirect_to accessory_categories_path
  end

private
  def accessory_params
    params.require(:accessory).permit(:name, :image)
  end
end

app/controllers/accessory_categories_controller.rb
class AccessoryCategoriesController < ApplicationController
	def index
		@accessory_categories = AccessoryCategory.all
	end

	def show
		@accessory_category = AccessoryCategory.find(params[:id])
    @accessories = @accessory_category.accessories
	end

	def new
		@accessory_category = AccessoryCategory.new
	end

	def edit
	end

	def create
		@accessory_category = AccessoryCategory.new(accessory_category_params)

    if @accessory_category.save
      redirect_to accessory_category_accessories_path(@accessory_category), notice: 'Accessory Category was successfully created.'
    else
      render :new
    end
	end

	def update
    if @accessory_category.update(accessory_params)
      redirect_to accessory_category_accessories_path(@accessory_category), notice: 'Accessory Category was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
  	@accessory_category = AccessoryCategory.find(params[:id])
    @accessory_category.destroy
    redirect_to accessory_categories_path, notice: 'Accessory Category was successfully destroyed.'
  end

private
  def accessory_category_params
    params.require(:accessory_category).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
	def index
    @inventory_category = InventoryCategory.find(params[:inventory_category_id])
		@inventories = @inventory_category.inventories
	end

	def show
    @inventory_category = InventoryCategory.find(params[:inventory_category_id])
		@inventory = @inventory_category.inventories.find(params[:id])
	end

	def new
		@inventory_category = InventoryCategory.find(params[:inventory_category_id])
    @inventory = @inventory_category.inventories.build
	end

	def edit
    @inventory_category = InventoryCategory.find(params[:inventory_category_id])
    @inventory = @inventory_category.inventories.find(params[:id])
	end

	def create
    @inventory_category = InventoryCategory.find(params[:inventory_category_id])
		@inventory = @inventory_category.inventories.build(inventory_params)

    if @inventory.save
      redirect_to inventory_categories_path, notice: 'Inventory was successfully created.'
    else
      render :new
    end
	end

	def update
    @inventory_category = InventoryCategory.find(params[:inventory_category_id])
    @inventory = @inventory_category.inventories.find(params[:id])

    if @inventory.update(inventory_params)
      redirect_to inventory_categories_path, notice: 'Inventory was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
  	@inventory_category = InventoryCategory.find(params[:inventory_category_id])
    @inventory = Inventory.find(params[:id])
    @inventory.destroy
    
    redirect_to inventory_categories_path
  end

private
  def inventory_params
    params.require(:inventory).permit(:name, :image)
  end

end

app/controllers/inventory_categories_controller.rb
class InventoryCategoriesController < ApplicationController
	def index
		@inventory_categories = InventoryCategory.all
	end

	def show
		@inventory_category = InventoryCategory.find(params[:id])
    @inventories = @inventory_category.inventories
	end

	def new
		@inventory_category = InventoryCategory.new
	end

	def edit
	end

	def create
		@inventory_category = InventoryCategory.new(inventory_category_params)

    if @inventory_category.save
      redirect_to inventory_category_inventories_path(@inventory_category), notice: 'Inventory Category was successfully created.'
    else
      render :new
    end
	end

	def update
    if @inventory_category.update(accessory_params)
      redirect_to inventory_category_inventories_path(@inventory_category), notice: 'Inventory Category was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
  	@inventory_category = InventoryCategory.find(params[:id])
    @inventory_category.destroy
    redirect_to inventory_categories_path, notice: 'Inventory Category was successfully destroyed.'
  end

  def destroy_inventory
    @inventory_category = InventoryCategory.find(params[:inventory_category_id])
    @inventory = Inventory.find(params[:id])
    @inventory.destroy
  end

private
  def inventory_category_params
    params.require(:inventory_category).permit(:name)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def home
	end

	def todolist
	end

	def all_inventory_offered
		@inventory_categories = InventoryCategory.all
		@accessory_categories = AccessoryCategory.all
	end
	
	def contact
	end

	def splash_page
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
	def first_image
		Inventory.where(name: 'Champagne Barback II').first
	end

	def second_image
		Accessory.where(name: 'Bar Serviceware II').first
	end
	
	def third_image
		Inventory.where(name: 'Julep Bar III').first
	end

	def fourth_image
		Accessory.where(name: 'Word Sign III').first
	end
end

app/views/accessories/_form.html.slim
.form-text
  = form_for ([@accessory_category, @accessory]), :html => { :multipart => true } do |f|
    - if @accessory.errors.any?
      div id="error_explanation"
        h2 
          = pluralize(@accessory.errors.count, "error")
          | prohibited this accessory from being saved:

        ul
          = @accessory.errors.full_messages.each do |message|
            li = message

    div.field
      = f.label :image 
      br
      = f.file_field :image

    div.field
      = f.label :name
      br
      = f.text_field :name

    div.actions
      = f.submit

app/views/accessories/edit.html.slim
h1 Editing Accessory

= render 'form'

= link_to 'Show', accessory_category_accessory_path(@accessory_category, @accessory)
br
= link_to 'Back', accessory_category_accessories_path(@accessory_category)

app/views/accessories/index.html.slim
.inventory
	.container
		.text-center
			h1 = @accessory_category.name
		ul style="list-style-type:none"
			- @accessories.each do |accessory|
				li.listed-inventory 
					= link_to(accessory_category_accessory_path(@accessory_category, accessory)) do
						- if accessory.image
							= image_tag accessory.image.url(:large)
						.text-center = accessory.name

		= link_to 'New', new_accessory_category_accessory_path
		br
		= link_to 'Delete', accessory_category_path(@accessory_category), method: :delete
		br
		= link_to 'Back', accessory_categories_path

app/views/accessories/new.html.slim
h1 New Accessory

= render 'form'

= link_to 'Back', accessory_category_accessories_path

app/views/accessories/show.html.slim
p id="notice"
  = notice

.text-center
  h1 = @accessory.name
  
  - if @accessory.image
    = link_to image_tag(@accessory.image.url(:large)), @accessory.image.url
  h4
    = link_to 'Edit', edit_accessory_category_accessory_path(@accessory_category.id, @accessory.id)
    br
    = link_to 'Delete', accessory_category_path(@accessory_category.id), method: :delete
    br
    = link_to 'Back', accessory_category_accessories_path

app/views/accessory_categories/_form.html.slim
= form_for @accessory_category, :html => { :multipart => true } do |f|
  - if @accessory_category.errors.any?
    div id="error_explanation"
      h2 
        = pluralize(@accessory_category.errors.count, "error")
        | prohibited this accessory category from being saved:

      ul
        = @accessory_category.errors.full_messages.each do |message|
          li = message

  div.field
    = f.label :name
    br
    = f.text_field :name

  div.actions
    = f.submit

app/views/accessory_categories/edit.html.slim
h1 Editing Accessory Category

= render 'form'

= link_to 'Show', @accessory_category
br
= link_to 'Back', accessory_categories_path

app/views/accessory_categories/index.html.slim
.inventory
	.container
		.text-center
			h1 Accessories

			- @accessory_categories.each do |accessory_category|
				.row
					h3 = accessory_category.name
					= link_to('Add accessory', new_accessory_category_accessory_path(accessory_category))
					.row
						- accessory_category.accessories.each do |accessory|
							.listed-inventory.col-sm-6.col-xs-12
								= image_tag accessory.image.url(:large)
								h4 = accessory.name
								br
								= link_to 'Edit', edit_accessory_category_accessory_path(accessory_category, accessory)
								br
								= link_to 'Delete', [accessory_category, accessory], method: :delete
				hr

		.clear-formatting 
			= link_to 'New', new_accessory_category_path

app/views/accessory_categories/new.html.slim
h1 New Accessory Category

= render 'form'

= link_to 'Back', accessory_categories_path

app/views/accessory_categories/show.html.slim
p id="notice"
  = notice

.text-center
  h1 = @accessory_category.name

ul style="list-style-type:none"
  - @accessories.each do |accessory|
    li.listed-inventory 
      = link_to(accessory_category_accessory_path(@accessory_category.id, accessory)) do
        - if accessory_category.accessories.first && accessory_category.accessories.first.image
          = image_tag accessory_category.accessories.first.image.url(:large)
        .text-center = accessory.name

h4.clear-formatting
  = link_to 'Edit', edit_accessory_category_path(@accessory_category.id)
  br
  = link_to 'Destroy', @accessory_category, method: :delete
  br
  = link_to 'Back', accessory_categories_path

app/views/inventories/_form.html.slim
.form-text
  = form_for ([@inventory_category, @inventory]), :html => { :multipart => true } do |f|
    - if @inventory.errors.any?
      div id="error_explanation"
        h2 
          = pluralize(@inventory.errors.count, "error")
          | prohibited this inventory from being saved:

        ul
          = @inventory.errors.full_messages.each do |message|
            li = message

    div.field
      = f.label :image 
      br
      = f.file_field :image

    div.field
      = f.label :name
      br
      = f.text_field :name

    div.actions
      = f.submit

app/views/inventories/edit.html.slim
h1 Editing Inventory

= render 'form'

= link_to 'Show', inventory_category_inventory_path(@inventory_category, @inventory)
br
= link_to 'Back', inventory_categories_path

app/views/inventories/index.html.slim
.inventory
	.container
		.text-center
			h1 = @inventory_category.name
		ul style="list-style-type:none"
			- @inventories.each do |inventory|
				li.listed-inventory 
					= link_to(inventory_category_inventory_path(@inventory_category.id, inventory)) do
						- if inventory.image
							= image_tag inventory.image.url(:large)
						.text-center = inventory.name

		= link_to 'New', new_inventory_category_inventory_path
		br
		= link_to 'Delete', inventory_category_path(@inventory_category), method: :delete
		br
		= link_to 'Back', inventory_categories_path

app/views/inventories/new.html.slim
h1 New Inventory

= render 'form'

= link_to 'Back', inventory_categories_path

app/views/inventories/show.html.slim
p id="notice"
	= notice

.text-center
  h1 = @inventory.name
  
  - if @inventory.image
	  = link_to image_tag(@inventory.image.url(:large)), @inventory.image.url
  h4
		= link_to 'Edit', edit_inventory_category_inventory_path(@inventory_category.id, @inventory)
		br
		= link_to 'Delete', inventory_category_inventory_path(@inventory_category, @inventory), method: :delete
		br
		= link_to 'Back', inventory_categories_path

app/views/inventory_categories/_form.html.slim
= form_for @inventory_category, :html => { :multipart => true } do |f|
  - if @inventory_category.errors.any?
    div id="error_explanation"
      h2 
        = pluralize(@inventory_category.errors.count, "error")
        | prohibited this accessory category from being saved:

      ul
        = @inventory_category.errors.full_messages.each do |message|
          li = message

  div.field
    = f.label :name
    br
    = f.text_field :name

  div.actions
    = f.submit

app/views/inventory_categories/edit.html.slim
h1 Editing Inventory Category

= render 'form'

= link_to 'Show', @inventory_category
= link_to 'Back', inventory_categories_path

app/views/inventory_categories/index.html.slim
.inventory
	.container
		.text-center
			h1 Inventory

			- @inventory_categories.each do |inventory_category|
				.row
					h3 = inventory_category.name
					= link_to('Add inventory', new_inventory_category_inventory_path(inventory_category))
					.row
						- inventory_category.inventories.each do |inventory|
							.listed-inventory.col-sm-6.col-xs-12
								= image_tag inventory.image.url(:large)
								h4 = inventory.name
								br
								= link_to 'Edit', edit_inventory_category_inventory_path(inventory_category, inventory)
								br
								= link_to 'Delete', [inventory_category, inventory], method: :delete

				hr

		.clear-formatting 
			= link_to 'New', new_inventory_category_path

app/views/inventory_categories/new.html.slim
h1 New Inventory Category

= render 'form'

= link_to 'Back', inventory_categories_path

app/views/inventory_categories/show.html.slim
p id="notice"
	= notice

.text-center
  h1 = @inventory_category.name

ul style="list-style-type:none"
  - @inventories.each do |inventory|
    li.listed-inventory 
      = link_to(inventory_category_inventory_path(@inventory_category.id, inventory.id)) do
        - if inventory.image
          = image_tag inventory.image.url(:large)
        .text-center = inventory.name

h4.clear-formatting
  = link_to 'Edit', edit_inventory_category_path(@inventory_category)
  br
  = link_to 'Destroy', @inventory_category, method: :delete
  br
  = link_to 'Back', inventory_categories_path

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <h2 class="pull-left"><%= link_to 'Happy Hour', home_path %></h2>
      <ul class="nav navbar-nav pull-right readable-text">
        <li><%= link_to 'Inventory', inventory_categories_path %></li>
        <li><%= link_to 'Accessories', accessory_categories_path %></li>
        <li><%= link_to 'Contact', contact_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Happy Hour</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <meta name="Description" CONTENT="Specializing in Unique Bar & Barback Rentals"/>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-88258327-1', 'auto');
      ga('send', 'pageview');

    </script>
  </head>
  <header>
    <div id="main-container" class="container">
      <div class="col header">
        <div class="text-center">
          <% #render partial: "layouts/navbar" %>
        </div>
      </div>
    </div>
  </header>
  <body class="<%= controller_name %> <%= action_name %>">
    <div id="main-container" class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/static_pages/all_inventory_offered.html.slim
h1 Happy Hour
h2.text-center Inventory
- @inventory_categories.each do |inventory_category|
	h3 = inventory_category.name
	ul 
		- inventory_category.inventories.each do |inventory|
			li = inventory.name
h2.text-center Accessories
- @accessory_categories.each do |accessory_category|
	h3 = accessory_category.name
	ul 
		- accessory_category.accessories.each do |accessory|
			li = accessory.name

app/views/static_pages/contact.html.slim
.text-center
	h1 Karla McCord
	h2 t: 206-920-1000
	h2 e: Karla@HappyHourBarRentals.com

app/views/static_pages/home.html.slim
//div.background_image.text-center
.homepage
	div.text-center
		h2 Making every hour of your special event Happy Hour
		= image_tag third_image.image.url(:large)

		h3 Lorem ipsum dolor sit amet, eu munere adipisci vix, eu sit nullam legere legendos, no dolore urbanitas assentior per. Mucius prompta apeirian id mei, in antiopam referrentur vim, elitr argumentum ad pro. Est invenire salutandi no, in illud posse everti cum. Eam cu porro numquam reprehendunt, per dicta oportere pericula.

		= image_tag second_image.image.url(:large)

		h3 Scaevola principes efficiendi pri ad, tractatos persequeris intellegebat cu eam, fabellas sadipscing no sit. Eu pri laboramus deseruisse, augue viderer platonem qui ei. Eleifend consulatu voluptatum id nam, ne quas ferri complectitur sit, an has posse option. Ut ferri tibique voluptatibus vix.

		= image_tag first_image.image.url(:large)

app/views/static_pages/splash_page.html.slim
.splashPage
	p.happy-hour-bar-rentals Happy Hour Designer Bar Rentals, Seattle, Bellevue, Kirkland, Washington, Weddings, Special Events
	.container
		.row
			.col-md-4
				.wording
					.logo
						.logoPhoto = image_tag("cropped_logo.png", alt: "Happy Hour Bar Rentals Logo")
						.visible-sm-down
							.mobileMainPhoto = image_tag("Champagne Bar- Debut Photo.png")
					hr
					.contactInfo.text-center.readable-text
						h4 For more information, please to contact:
						h4 
							| (425) 310-2269
						h4 karla@happyhourbarrentals.com
						hr
						h5 ~ Serve your Cocktails with Class ~
						h5 Specializing in Unique Bar & Barback Rentals 
						h5 Personalize by adding your own Monogram and/or Logo
						p.happy-hour-bar-rentals Happy Hour Designer Bar Rentals Happy Hour Bar Rentals
						h5 Why Limit Happy to Just an Hour?


						.facebookLogo
							= link_to(image_tag("facebook_logo.png"), "https://www.facebook.com/Happy-Hour-Designer-Bar-Rentals-1300043366712918/", target: "_blank", alt: "Happy Hour Designer Bar Rental")
				.bottomLeftImage = image_tag("julep_bar3.jpg", alt: "Happy Hour Designer Bar Rental")
			.col-md-8
				.hidden-sm-down
					.splashPage-mainPhoto
						= image_tag("Champagne Bar- Debut Photo.png", alt: "Happy Hour Designer Bar Rental")

app/views/static_pages/todolist.html.slim
h1 TODO List:

h3 Soon
ul
	li Authorization (ability to sign in/out - only show some content when signed in as an Admin)
	li Add contact page

h3 In the future
ul
	li Add links to FB, Instagram, Pinterest
	li Add contact form